config/routes.rb
Resistance::Application.routes.draw do
  get "player/ready"

  root 'games#index'
  
  post 'games/create'    => 'games#create'
  post 'games/join'    => 'games#join'
  get 'lobby/:id' => 'games#lobby'
  get 'games/:id' => 'games#game', :as => "game"
  get 'games/submit_team/:id' => 'games#submit_team', :as => "submit_team"
  get 'games/submit_team_vote/:id/:vote' => 'games#submit_team_vote', :as => "submit_team_vote"
  get 'games/submit_mission_vote/:id/:vote' => 'games#submit_mission_vote', :as => "submit_mission_vote"
  
  get 'players/ready' => 'players#ready'
  get 'players/change_name' => 'players#change_name'
  get 'players/toggle_team/:id' => 'players#toggle_team', :as => "add_to_team"

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players, :dependent => :destroy
  has_many :rounds, :dependent => :destroy
  belongs_to :current_round, :class_name => "Round", :foreign_key => :current_round_id
  
  attr_accessor :leader
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  SPY_NUMBERS = {
    "2" => 1,
    "3" => 2,
    "4" => 2,
    
    "5" => 2,
    "6" => 2,
    "7" => 3,
    "8" => 3,
    "9" => 3,
    "10" => 4
  }
  
  MISSION_COUNT = {
    "2" => [2, 2, 2, 2, 2],
    "3" => [2, 2, 2, -2, 2],
    "4" => [2, 2, 2, -3, 3],
    
    "5" => [2, 3, 2, 3, 3],
    "6" => [2, 3, 4, 3, 4],
    "7" => [2, 3, 3, -4, 4],
    "8" => [3, 4, 4, -5, 5],
    "9" => [3, 4, 4, -5, 5],
    "10" => [3, 4, 4, -5, 5]
  }  
  
  module States
    LEADER       = 0
    TEAM_VOTE    = 1
    MISSION_VOTE = 2
    ENDED        = 3
  end
  
  
  def round_num
    neg_score + pos_score + 1
  end
  
  def team_num
    MISSION_COUNT[players.count.to_s][round_num - 1].abs
  end
  
  def double_fail_round?
    MISSION_COUNT[players.count.to_s][round_num - 1] < 0
  end
  
  def is_over?
    return neg_score >= 3 || pos_score >= 3 
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    session[:game_ended] = nil
  end
  
  def create
    game = Game.create!( :name => params[:game_name] )
    session[:auth] = SecureRandom.uuid
    player = Player.create!( :game => game, :name => params[:player_name].present? ? params[:player_name] : "Player1", :auth_hash => session[:auth] )
    redirect_to :action => "lobby", :id => game.id
  end
  
  def join
    game = Game.find_by_name( params[:game_name] )
    raise "No game found by the name of '#{params[:game_name]}'" if game.nil?
    
    if game.is_active? 
      if current_player.try( :game_id ) != game.id
        raise "This game is already in session" 
      else
        redirect_to :action => "game", :id => game.id
        return
      end
    end
    session[:auth] = SecureRandom.uuid
    player = Player.create!( :game => game, :name => params[:player_name].present? ? params[:player_name] : "Player#{game.players.count + 1}", :auth_hash => session[:auth] )
    
    js_res = "
      $( '.lobby_table' ).append( '<tr><td>#{player.name}</td><td><div id=\"player_#{player.id}_ready\" class=\"label label-important\">Not Ready</div></td></tr>' );
    "
  
    PrivatePub.publish_to "/lobby/#{game.id}", js_res
    redirect_to :action => "lobby", :id => game.id
  end

  def lobby
    raise "You don't belong here!" unless params[:id].present? && session[:auth].present?
    @game = Game.find( params[:id] )
    @player = Player.find_by_auth_hash( session[:auth] )
  end
  
  def game
    begin
      @game = Game.find( params[:id] )
    rescue
      redirect_to :action => 'index'
      return
    end
    
    @players = @game.players.order("id")
    
    if !@game.is_active? && !@game.is_over?
      redirect_to :action => "lobby", :id => @game.id
      return
    end
    
    raise "You aren't in this game!" unless @players.pluck( :auth_hash ).include? session[:auth]
    
    if @game.is_over? && @game.is_active?
      @game.update_attributes!( :state => Game::States::ENDED, :is_active => false )
    end
    
    case @game.state
    when Game::States::LEADER
      if @game.current_round_id.blank?
        @game.current_round = Round.create( :leader => @players.first, :game => @game )  
        @game.save!
      elsif ( !@game.current_round.passed_team_vote? && @game.current_round.has_votes? ) || @game.current_round.has_mission_votes?
        new_round = Round.create( :leader => next_leader( @game, @game.current_round.leader ), :game => @game )  
        @game.update_attributes!( :current_round_id => new_round.id )
      end
    when Game::States::TEAM_VOTE
      @team_players = @players.select{ |p| @game.current_round.team_ids.include? p.id }
    when Game::States::MISSION_VOTE
      @team_players = @players.select{ |p| @game.current_round.team_ids.include? p.id }
    when Game::States::ENDED
      if session[:game_ended].present?
        redirect_to :action => 'index'
        return
      end
      session[:game_ended] = "true"
    end
    
    @round = @game.current_round
  end
  
  def submit_team
    game = Game.find( params[:id] )
    game.update_attributes!( :state => Game::States::TEAM_VOTE )
    
    game.current_round.update_attributes!( :who_voted => nil )
    
    PrivatePub.publish_to "/game/#{game.id}", "location.reload();"
    
    render :text => "done"
  end
  
  def submit_team_vote
    game = Game.find( params[:id] )
    
    raise "You can't do this" unless game.state == Game::States::TEAM_VOTE || game.current_round_id.blank?
    
    round = game.current_round
    if params[:vote] == "yes"
      round.who_voted << current_player.id
      round.update_attributes!( :yes_votes => round.yes_votes.to_i + 1 )
    elsif params[:vote] == "no"
      round.who_voted << current_player.id
      round.update_attributes!( :no_votes => round.no_votes.to_i + 1 )
    else
      raise "You're doing it wrong"
    end
    
    PrivatePub.publish_to "/game/#{game.id}", "$( '.total_votes' ).html( '#{round.total_team_votes}' )"
    PrivatePub.publish_to "/game/player/#{current_player.id}", "$( '.vote_options' ).hide();"
    
    if round.total_team_votes >= game.players.count # all votes in
      if round.passed_team_vote?
        round.update_attributes!( :who_voted => nil )
        game.update_attributes!( :state => Game::States::MISSION_VOTE )
        PrivatePub.publish_to "/game/#{game.id}", "alert( 'YES' );"
      else
        game.update_attributes!( :state => Game::States::LEADER )
        PrivatePub.publish_to "/game/#{game.id}", "alert( 'NO' );"
      end
      PrivatePub.publish_to "/game/#{game.id}", "location.reload();"
    end

    render :text => "done"
  end
  
  def submit_mission_vote
    game = Game.find( params[:id] )
    
    raise "You can't do this" unless game.state == Game::States::MISSION_VOTE || game.current_round_id.blank?
    
    round = game.current_round
    if params[:vote] == "pass"
      round.who_voted << current_player.id
      round.update_attributes!( :pass_votes => round.pass_votes.to_i + 1 )
    elsif params[:vote] == "fail"
      round.who_voted << current_player.id
      round.update_attributes!( :fail_votes => round.fail_votes.to_i + 1 )
    else
      raise "You're doing it wrong"
    end
    
    PrivatePub.publish_to "/game/#{game.id}", "$( '.total_votes' ).html( '#{round.total_mission_votes}' )"
    PrivatePub.publish_to "/game/player/#{current_player.id}", "$( '.vote_options' ).hide();"
    
    if round.total_mission_votes >= round.team_ids.count # all votes in
      if round.passed_mission_vote?
        game.update_attributes!( :pos_score => game.pos_score + 1, :state => Game::States::LEADER )
        PrivatePub.publish_to "/game/#{game.id}", "alert( 'PASSED' );"
      else
        game.update_attributes!( :neg_score => game.neg_score + 1, :state => Game::States::LEADER )
        PrivatePub.publish_to "/game/#{game.id}", "alert( 'FAILED' );"
      end
        
      PrivatePub.publish_to "/game/#{game.id}", "location.reload();"
    end

    render :text => "done"
  end
  
  

  private
  
  
  def next_leader( game, leader )
    players = game.players.order( "id" ).all
    
    idx = players.find_index( leader ) + 1
    if idx == players.count
      players.first
    else
      players[idx]
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_game_state_0.html.haml
%h4 Leader

%ul.player_list
  - @players.each do |player|
    - is_this_player = player.auth_hash == session[:auth]
    %li.player_item
      - if @round.leader == player
        &#9733;
      - if is_this_player
        %strong= player.name
      - else
        = player.name
      %span{ :id => "player_#{player.id}_in_round" }
        - if @round.team_ids.include? player.id
          &#9996;
      - if @round.leader == current_player
        = link_to "Add to Team", add_to_team_path( :id => player.id ), :remote => true, :class => "add_team_link"

- if @round.leader == current_player
  = link_to "Go to Vote", submit_team_path( :id => @game.id ), :remote => true, :class => "submit_team_link #{@round.team_num == @game.team_num ? "" : "hidden" }"

app/views/games/_game_state_1.html.haml
TEAM VOTE STATE

app/views/games/_game_state_2.html.haml
%h4 Mission Vote

- if @game.double_fail_round?
  %h5 Need 2 fails to fails
- else
  %h5 Need 1 fail to fail

%ul.player_list
  - @team_players.each do |player|
    - is_this_player = player.auth_hash == session[:auth]
    %li.player_item
      - if @round.leader == player
        &#9733;
      - if is_this_player
        %strong= player.name
      - else
        = player.name
        
%h5 Not in vote
%ul.player_list
  - @players.reject{ |p| @team_players.include? p }.each do |player|
    - is_this_player = player.auth_hash == session[:auth]
    %li.player_item
      - if @round.leader == player
        &#9733;
      - if is_this_player
        %strong= player.name
      - else
        = player.name
        
.vote_count
  Votes:
  %span.total_votes= @round.total_mission_votes 
  \/
  = @team_players.count
  
- if !@round.who_voted.include?( current_player.id ) && @team_players.include?( current_player )
  .vote_options
    = link_to "Pass", submit_mission_vote_path( :id => @game.id, :vote => "pass" ), :remote => true, :class => "submit_mission_vote_link btn btn-primary"
    = link_to "Fail", submit_mission_vote_path( :id => @game.id, :vote => "fail" ), :remote => true, :class => "submit_mission_vote_link btn btn-danger"

app/views/games/_game_state_3.html.haml
%h4 
  Game Over:
  - if @game.pos_score > @game.neg_score
    GOOD GUYS WIN
  - else
    SPIES WIN
%ul.player_list
  - @players.each do |player|
    - is_this_player = player.auth_hash == session[:auth]
    %li.player_item{ :class => player.loyalty == 0 ? "" : "spy" }
      - if is_this_player
        %strong= player.name
      - else
        = player.name

app/views/games/game.html.haml
%h3= "#{@game.name}: round #{@game.round_num} state: #{@game.state}"

%h5 
  Score: 
  %span.good_score= @game.pos_score
  \/
  %span.bad_score= @game.neg_score

= render :partial => "game_state_#{@game.state}"

- if current_player.loyalty == 0
  You're a GOOD GUY
- else
  You're a SPY
          
= subscribe_to "/game/#{@game.id}"
= subscribe_to "/game/player/#{current_player.id}"
  

      

app/views/games/index.html.haml
.hero-unit
  %h1 Welcome
  %p.lead Create a new Game or join a current Game
  %p
    .create_game.btn Create
    .join_game.btn Join
  = form_tag "games/create", :method => :post, :class => "hidden game_form" do
    = text_field_tag 'game_name', "", :style => "margin-bottom:0;", :placeholder => "Game name", :required => "required"
    = submit_tag "Go", :class => "btn btn-small"
    %br
    = text_field_tag 'player_name', "", :style => "margin-bottom:0;", :placeholder => "Username"
  
:javascript
  $( function() {
    $( '.create_game, .join_game' ).on( 'click', function() {
    
      $( '.create_game, .join_game' ).removeClass( 'active' ).removeClass( 'btn-success' );
      
      var btn = $( this ).addClass( 'active' ).addClass( 'btn-success' ),
          form = $( '.game_form' ).removeClass( 'hidden' );
      
      if( btn.hasClass( 'create_game' ) ) {
        form.attr( 'action', 'games/create' );
      } else {
        form.attr( 'action', 'games/join' );
      }
      
    });
  });

app/views/games/lobby.html.haml
%h2= @game.name
%table.table.table-hover.table-striped.table-bordered.lobby_table
  - @game.players.each do |player|
    - is_this_player = player.auth_hash == session[:auth]
    %tr
      %td{ :id => "player_#{player.id}_name" }
        %span.player_name
          - if is_this_player
            %strong= player.name
          - else
            = player.name
        - if is_this_player
          %span.player_name_field.hidden
            = text_field_tag "player_#{player.id}_name_field", "", :placeholder => "Enter new name", :style => "margin-bottom:0"
            = link_to "Change", '/players/change_name', :remote => true, :class => "btn btn-small"
            .btn.btn-small.cancel_player_name Cancel
      - rdy = player.is_ready?
      %td
        - if is_this_player
          = link_to rdy ? "Ready" : "Not Ready", "/players/ready", :remote => true, :id => "player_#{player.id}_ready", :class => "btn btn-small ready_button #{rdy ? "btn-success" : "btn-danger"}"
        - else
          .label{ :id => "player_#{player.id}_ready", :class => rdy ? "label-success" : "label-important" }= rdy ? "Ready" : "Not Ready"
        
        
= subscribe_to "/lobby/#{@game.id}"

:javascript
  $( function() {
    $( '.lobby_table' ).on( 'click', '.ready_button', function() {
      if( $( '.ready_button' ).length == $( '.ready_button.btn-success' ).length ) {
        alert( "Everyone is ready, you can't unready now" );
        return false; 
      }
    });
    
    $( '.lobby_table' ).on( 'click', '.player_name', function() {
      if( $( this ).next().is( '.player_name_field' ) )
        $( this ).addClass( 'hidden' ).next().removeClass( 'hidden' ).focus();
    });
  
    $( '.lobby_table' ).on( 'keyup', '.player_name_field input', function() {
      $( this ).next().attr( 'href', '/players/change_name?player_name=' + this.value );
    });
    
    /// cancel name change

  });